- uses: Platane/snk@v3
  with:
    github_user_name: SmiChau
    outputs: |
      dist/snake-soft.svg?color_snake=#7aa2f7&color_dots=#e3f2fd,#bbdefb,#90caf9,#64b5f6,#42a5f5
      dist/snake-pastel.svg?color_snake=#c084fc&color_dots=#f3e8ff,#e9d5ff,#d8b4fe,#c084fc,#a855f7
      dist/snake-dark-neon.svg?palette=github-dark&color_snake=#00f5d4&color_dots=#1a1b27,#243b55,#00c9a7,#00f5d4,#72efdd
